language: node_js
sudo: required
dist: xenial
node_js:
  - "8"
jdk:
  - oraclejdk11
env:
  global:
    - COVERALLS=1
    - WAIT_FOR_ES=1
  matrix:
    - ES_VERSION=7.3.2
install:
  - mkdir /tmp/elasticsearch
  - wget -O - https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}-linux-x86_64.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1
  - /tmp/elasticsearch/bin/elasticsearch --daemonize -E path.data=/tmp
  - until curl --silent -XGET --fail http://localhost:9200; do printf '.'; sleep 1; done
  - npm install
git:
  depth: 10
before_install:
  - echo $JAVA_HOME
  - java -version
before_script:
  - sleep 10
after_success:
  - 'npm run coveralls'
  - 'cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'
